### ISSUE TITLE
Use Slice

### ISSUE THREAD

**Issue by unacowa** [kamiazya/nlp100#1]
https://github.com/kamiazya/nlp100/blob/190366a4d4ca86c2db921018c3f5f03bd47d77be/src/ch1/_01/patatokukashi.py#L8

```
>>> "パタトクカシーー"[::2]
'パトカー'
>>> "パタトクカシーー"[1::2]
'タクシー'
```

**Comment by kamiazya** [comment]
ありがとうございます！

要件の字面通りの実装を意識して作ったのでスライスは使っていなかったのですが、スライスを使ったバージョンも作ってみたいと思います。
